databases:
  - name: airbne
    user: airbne
    plan: free
    region: oregon

services:
  - type: web
    name: airbne
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/strt-build.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airbne
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false